/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangmangame;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class HangmanGUI extends javax.swing.JFrame
{

    Connect connect = new Connect();
    ImageIcon stickman = new ImageIcon(getClass().getResource("/images/imageiconmain.png"));
    ImageIcon head = new ImageIcon(getClass().getResource("/images/head.jpg"));
    ImageIcon body = new ImageIcon(getClass().getResource("/images/body.png"));
    ImageIcon arm1 = new ImageIcon(getClass().getResource("/images/arm1.png"));
    ImageIcon arm2 = new ImageIcon(getClass().getResource("/images/arm2.png"));
    ImageIcon leg1 = new ImageIcon(getClass().getResource("/images/leg1.png"));
    ImageIcon leg2 = new ImageIcon(getClass().getResource("/images/leg2.png"));
    Object lvl = "";
    Play play = new Play("", "", "", 0, 6, 0);
    int phrases1, phrases2, phrases3 = 0;
    String display = "";

    public void refresh()
    {
        //reset everything so that the user can play again without exiting
        btnA.setEnabled(true);
        btnB.setEnabled(true);
        btnC.setEnabled(true);
        btnD.setEnabled(true);
        btnE.setEnabled(true);
        btnF.setEnabled(true);
        btnG.setEnabled(true);
        btnH.setEnabled(true);
        btnI.setEnabled(true);
        btnJ.setEnabled(true);
        btnK.setEnabled(true);
        btnL.setEnabled(true);
        btnM.setEnabled(true);
        btnN.setEnabled(true);
        btnO.setEnabled(true);
        btnP.setEnabled(true);
        btnQ.setEnabled(true);
        btnR.setEnabled(true);
        btnS.setEnabled(true);
        btnT.setEnabled(true);
        btnU.setEnabled(true);
        btnV.setEnabled(true);
        btnW.setEnabled(true);
        btnX.setEnabled(true);
        btnY.setEnabled(true);
        btnZ.setEnabled(true);

        lblWord.setText("");
        lblGuesses.setText("");
        lblDisplayScore.setText("");
        lblHead.setIcon(null);
        lblBody.setIcon(null);
        lblArm1.setIcon(null);
        lblArm2.setIcon(null);
        lblLeg1.setIcon(null);
        lblLeg2.setIcon(null);

        display = "";
        play.setScore(0);
    }

    /**
     * Creates new form HangmanGUI
     */
    public HangmanGUI()
    {
        initComponents();
        setIconImage(stickman.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        frmGoodbye = new javax.swing.JFrame();
        lblWavingHand = new javax.swing.JLabel();
        lblThanks = new javax.swing.JLabel();
        btnOK1 = new javax.swing.JButton();
        lblBackground1 = new javax.swing.JLabel();
        frmLogin = new javax.swing.JFrame();
        lblUsername = new javax.swing.JLabel();
        txfUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txfPassword = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnBackLogin = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        frmPlay = new javax.swing.JFrame();
        lblHead = new javax.swing.JLabel();
        lblBody = new javax.swing.JLabel();
        lblArm2 = new javax.swing.JLabel();
        lblArm1 = new javax.swing.JLabel();
        lblLeg2 = new javax.swing.JLabel();
        lblLeg1 = new javax.swing.JLabel();
        btnA = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        btnExitGame = new javax.swing.JButton();
        lblWord = new javax.swing.JLabel();
        lblGuesses = new javax.swing.JLabel();
        lblDisplayScore = new javax.swing.JLabel();
        lblParchment = new javax.swing.JLabel();
        lblPlayBackground = new javax.swing.JLabel();
        frmHighscores = new javax.swing.JFrame();
        lblHighscoresTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaHighscores = new javax.swing.JTextArea();
        btnLevel1 = new javax.swing.JButton();
        btnLevel2 = new javax.swing.JButton();
        btnLevel3 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack2 = new javax.swing.JButton();
        txfDeleteUser = new javax.swing.JTextField();
        btnDeleteUser = new javax.swing.JButton();
        lblHighscoresBackground = new javax.swing.JLabel();
        frmWordEditor = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaWordEditorView = new javax.swing.JTextArea();
        lblWordEditorTitle = new javax.swing.JLabel();
        txfInsert = new javax.swing.JTextField();
        cmbInsert = new javax.swing.JComboBox<>();
        btnInsert = new javax.swing.JButton();
        txfUpdate = new javax.swing.JTextField();
        cmbUpdate = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        txfDelete = new javax.swing.JTextField();
        cmbDelete = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        txfUpdate2 = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblWordEditorBackground = new javax.swing.JLabel();
        frmRegister = new javax.swing.JFrame();
        lblRegisterUser = new javax.swing.JLabel();
        lblRegisterPass = new javax.swing.JLabel();
        txfRegisterUser = new javax.swing.JTextField();
        txfRegisterPass = new javax.swing.JTextField();
        btnRegister2 = new javax.swing.JButton();
        btnCancelRegister = new javax.swing.JButton();
        lblRegisterBackground = new javax.swing.JLabel();
        frmWin = new javax.swing.JFrame();
        lblThumbsUp = new javax.swing.JLabel();
        lblGoodJob = new javax.swing.JLabel();
        btnOKWin = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        lblWinBackground = new javax.swing.JLabel();
        frmLose = new javax.swing.JFrame();
        lblSorryFace = new javax.swing.JLabel();
        lblSorry = new javax.swing.JLabel();
        btnOKLoss = new javax.swing.JButton();
        lblFailedWord = new javax.swing.JLabel();
        lblLossBackground = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        btnPlay = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnHighScores = new javax.swing.JButton();
        btnWordEditor = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblMainBackground = new javax.swing.JLabel();

        frmGoodbye.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frmGoodbye.setTitle("Goodbye");
        frmGoodbye.setMinimumSize(new java.awt.Dimension(400, 240));
        frmGoodbye.setResizable(false);
        frmGoodbye.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWavingHand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goodbyehand.jpg"))); // NOI18N
        lblWavingHand.setMaximumSize(new java.awt.Dimension(50, 50));
        lblWavingHand.setMinimumSize(new java.awt.Dimension(50, 50));
        frmGoodbye.getContentPane().add(lblWavingHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 170));

        lblThanks.setText("Thanks for playing hangman!");
        frmGoodbye.getContentPane().add(lblThanks, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        btnOK1.setText("OK");
        btnOK1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOK1ActionPerformed(evt);
            }
        });
        frmGoodbye.getContentPane().add(btnOK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        lblBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paperbackground.jpg"))); // NOI18N
        frmGoodbye.getContentPane().add(lblBackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        frmLogin.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frmLogin.setTitle("Login");
        frmLogin.setMinimumSize(new java.awt.Dimension(400, 240));
        frmLogin.setSize(new java.awt.Dimension(400, 240));
        frmLogin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setText("Username:");
        frmLogin.getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txfUsername.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txfUsernameActionPerformed(evt);
            }
        });
        frmLogin.getContentPane().add(txfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 300, -1));

        lblPassword.setText("Password:");
        frmLogin.getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        frmLogin.getContentPane().add(txfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 300, -1));

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOKActionPerformed(evt);
            }
        });
        frmLogin.getContentPane().add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegisterActionPerformed(evt);
            }
        });
        frmLogin.getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        btnBackLogin.setText("BACK");
        btnBackLogin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBackLoginActionPerformed(evt);
            }
        });
        frmLogin.getContentPane().add(btnBackLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paperbackground.jpg"))); // NOI18N
        frmLogin.getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        frmPlay.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frmPlay.setTitle("Play Hangman");
        frmPlay.setMinimumSize(new java.awt.Dimension(610, 435));
        frmPlay.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        frmPlay.getContentPane().add(lblHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 50, 40));
        frmPlay.getContentPane().add(lblBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 10, 60));
        frmPlay.getContentPane().add(lblArm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 50, 10));
        frmPlay.getContentPane().add(lblArm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 50, 10));
        frmPlay.getContentPane().add(lblLeg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 200, 40, 40));
        frmPlay.getContentPane().add(lblLeg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 200, 40, 40));

        btnA.setText("A");
        btnA.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 40, -1));

        btnB.setText("B");
        btnB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 40, -1));

        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 40, -1));

        btnD.setText("D");
        btnD.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnD, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 40, -1));

        btnE.setText("E");
        btnE.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 40, -1));

        btnF.setText("F");
        btnF.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnF, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 40, -1));

        btnG.setText("G");
        btnG.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnG, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 40, -1));

        btnH.setText("H");
        btnH.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnH, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 40, -1));

        btnI.setText("I");
        btnI.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnI, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 40, -1));

        btnJ.setText("J");
        btnJ.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 40, -1));

        btnL.setText("L");
        btnL.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnL, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 40, -1));

        btnK.setText("K");
        btnK.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnK, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 40, -1));

        btnM.setText("M");
        btnM.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnM, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 40, -1));

        btnN.setText("N");
        btnN.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 40, -1));

        btnO.setText("O");
        btnO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnO, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 40, -1));

        btnP.setText("P");
        btnP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 40, -1));

        btnQ.setText("Q");
        btnQ.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 40, -1));

        btnR.setText("R");
        btnR.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnR, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 40, -1));

        btnS.setText("S");
        btnS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnS, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 40, -1));

        btnT.setText("T");
        btnT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnT, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 40, -1));

        btnU.setText("U");
        btnU.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnU, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 40, -1));

        btnV.setText("V");
        btnV.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnV, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 40, -1));

        btnW.setText("W");
        btnW.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnW, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 42, -1));

        btnX.setText("X");
        btnX.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 220, 38, -1));

        btnY.setText("Y");
        btnY.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnY, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 40, -1));

        btnZ.setText("Z");
        btnZ.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 40, -1));

        btnExitGame.setText("EXIT");
        btnExitGame.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExitGameActionPerformed(evt);
            }
        });
        frmPlay.getContentPane().add(btnExitGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 80, -1));

        lblWord.setFont(new java.awt.Font("Blackadder ITC", 1, 24)); // NOI18N
        lblWord.setText("word");
        frmPlay.getContentPane().add(lblWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 240, 20));

        lblGuesses.setFont(new java.awt.Font("Blackadder ITC", 1, 24)); // NOI18N
        lblGuesses.setText("guesses");
        frmPlay.getContentPane().add(lblGuesses, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 240, 20));

        lblDisplayScore.setFont(new java.awt.Font("Blackadder ITC", 1, 24)); // NOI18N
        lblDisplayScore.setText("score");
        frmPlay.getContentPane().add(lblDisplayScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 240, 20));

        lblParchment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/parchment.jpg"))); // NOI18N
        frmPlay.getContentPane().add(lblParchment, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 240, 100));

        lblPlayBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainmenubackground.png"))); // NOI18N
        frmPlay.getContentPane().add(lblPlayBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        frmHighscores.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frmHighscores.setTitle("Highscores");
        frmHighscores.setMinimumSize(new java.awt.Dimension(600, 430));
        frmHighscores.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHighscoresTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblHighscoresTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHighscoresTitle.setText("HIGHSCORES");
        frmHighscores.getContentPane().add(lblHighscoresTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 410, 40));

        txaHighscores.setEditable(false);
        txaHighscores.setColumns(20);
        txaHighscores.setRows(5);
        jScrollPane2.setViewportView(txaHighscores);

        frmHighscores.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 560, 270));

        btnLevel1.setText("Level 1");
        btnLevel1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLevel1ActionPerformed(evt);
            }
        });
        frmHighscores.getContentPane().add(btnLevel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        btnLevel2.setText("Level 2");
        btnLevel2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLevel2ActionPerformed(evt);
            }
        });
        frmHighscores.getContentPane().add(btnLevel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        btnLevel3.setText("Level 3");
        btnLevel3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLevel3ActionPerformed(evt);
            }
        });
        frmHighscores.getContentPane().add(btnLevel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnClearActionPerformed(evt);
            }
        });
        frmHighscores.getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        btnBack2.setText("BACK");
        btnBack2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBack2ActionPerformed(evt);
            }
        });
        frmHighscores.getContentPane().add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        txfDeleteUser.setText("Enter username to delete...");
        frmHighscores.getContentPane().add(txfDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 226, -1));

        btnDeleteUser.setText("DELETE");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDeleteUserActionPerformed(evt);
            }
        });
        frmHighscores.getContentPane().add(btnDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        lblHighscoresBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/functionbackgroundresized.jpg"))); // NOI18N
        frmHighscores.getContentPane().add(lblHighscoresBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        frmWordEditor.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frmWordEditor.setTitle("Word Editor");
        frmWordEditor.setMinimumSize(new java.awt.Dimension(600, 433));
        frmWordEditor.setResizable(false);
        frmWordEditor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txaWordEditorView.setEditable(false);
        txaWordEditorView.setColumns(20);
        txaWordEditorView.setRows(5);
        jScrollPane3.setViewportView(txaWordEditorView);

        frmWordEditor.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 570, 220));

        lblWordEditorTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblWordEditorTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWordEditorTitle.setText("WORD EDITOR");
        frmWordEditor.getContentPane().add(lblWordEditorTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 420, 50));

        txfInsert.setText("New Word");
        txfInsert.setToolTipText("");
        frmWordEditor.getContentPane().add(txfInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 170, -1));

        cmbInsert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3" }));
        cmbInsert.setToolTipText("");
        frmWordEditor.getContentPane().add(cmbInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        btnInsert.setText("INSERT");
        btnInsert.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnInsertActionPerformed(evt);
            }
        });
        frmWordEditor.getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        txfUpdate.setText("Current Word");
        txfUpdate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txfUpdateActionPerformed(evt);
            }
        });
        frmWordEditor.getContentPane().add(txfUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 170, -1));

        cmbUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3" }));
        frmWordEditor.getContentPane().add(cmbUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnUpdateActionPerformed(evt);
            }
        });
        frmWordEditor.getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        txfDelete.setText("Current Word");
        txfDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txfDeleteActionPerformed(evt);
            }
        });
        frmWordEditor.getContentPane().add(txfDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 170, -1));

        cmbDelete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3" }));
        frmWordEditor.getContentPane().add(cmbDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDeleteActionPerformed(evt);
            }
        });
        frmWordEditor.getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn1ActionPerformed(evt);
            }
        });
        frmWordEditor.getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn2ActionPerformed(evt);
            }
        });
        frmWordEditor.getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn3ActionPerformed(evt);
            }
        });
        frmWordEditor.getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        txfUpdate2.setText("New Word");
        txfUpdate2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txfUpdate2ActionPerformed(evt);
            }
        });
        frmWordEditor.getContentPane().add(txfUpdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 170, -1));

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBackActionPerformed(evt);
            }
        });
        frmWordEditor.getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 280, -1, -1));

        lblWordEditorBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/functionbackgroundresized.jpg"))); // NOI18N
        frmWordEditor.getContentPane().add(lblWordEditorBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        frmRegister.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frmRegister.setTitle("Register");
        frmRegister.setMinimumSize(new java.awt.Dimension(400, 240));
        frmRegister.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegisterUser.setText("Username:");
        frmRegister.getContentPane().add(lblRegisterUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblRegisterPass.setText("Password:");
        frmRegister.getContentPane().add(lblRegisterPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        frmRegister.getContentPane().add(txfRegisterUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 300, -1));
        frmRegister.getContentPane().add(txfRegisterPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 300, -1));

        btnRegister2.setText("REGISTER");
        btnRegister2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegister2ActionPerformed(evt);
            }
        });
        frmRegister.getContentPane().add(btnRegister2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        btnCancelRegister.setText("CANCEL");
        btnCancelRegister.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelRegisterActionPerformed(evt);
            }
        });
        frmRegister.getContentPane().add(btnCancelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        lblRegisterBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/functionbackground.jpg"))); // NOI18N
        frmRegister.getContentPane().add(lblRegisterBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 240));

        frmWin.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frmWin.setTitle("You Won!");
        frmWin.setMinimumSize(new java.awt.Dimension(410, 240));
        frmWin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThumbsUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thumbsupresized.jpg"))); // NOI18N
        lblThumbsUp.setText("jLabel1");
        frmWin.getContentPane().add(lblThumbsUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 170));

        lblGoodJob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGoodJob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGoodJob.setText("Good Job!");
        frmWin.getContentPane().add(lblGoodJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 40, 210, -1));

        btnOKWin.setText("OK");
        btnOKWin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOKWinActionPerformed(evt);
            }
        });
        frmWin.getContentPane().add(btnOKWin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 60, -1));

        lblScore.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScore.setText("Score here");
        frmWin.getContentPane().add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 190, -1));

        lblWinBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/functionbackground.jpg"))); // NOI18N
        frmWin.getContentPane().add(lblWinBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 240));

        frmLose.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frmLose.setTitle("Better Luck Next Time!");
        frmLose.setMinimumSize(new java.awt.Dimension(400, 240));
        frmLose.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSorryFace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sorryresized.jpg"))); // NOI18N
        lblSorryFace.setText("jLabel3");
        frmLose.getContentPane().add(lblSorryFace, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 170));

        lblSorry.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSorry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSorry.setText("Sorry! Your word was:");
        frmLose.getContentPane().add(lblSorry, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 150, 20));

        btnOKLoss.setText("OK");
        btnOKLoss.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOKLossActionPerformed(evt);
            }
        });
        frmLose.getContentPane().add(btnOKLoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        lblFailedWord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFailedWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFailedWord.setText("Failed word here");
        frmLose.getContentPane().add(lblFailedWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 160, 20));

        lblLossBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/functionbackground.jpg"))); // NOI18N
        frmLose.getContentPane().add(lblLossBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 240));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 400));

        jPanel1.setMinimumSize(new java.awt.Dimension(600, 400));

        jLayeredPane2.setMinimumSize(new java.awt.Dimension(600, 400));
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPlay.setText("PLAY");
        btnPlay.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPlayActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExitActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        btnHighScores.setText("HIGHSCORES");
        btnHighScores.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnHighScoresActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btnHighScores, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        btnWordEditor.setText("WORD EDITOR");
        btnWordEditor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnWordEditorActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btnWordEditor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HangmanTitle.png"))); // NOI18N
        lblTitle.setText("jLabel3");
        jLayeredPane2.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 347, 79));

        lblMainBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainmenubackground.png"))); // NOI18N
        lblMainBackground.setText("background");
        lblMainBackground.setMaximumSize(new java.awt.Dimension(600, 400));
        lblMainBackground.setMinimumSize(new java.awt.Dimension(600, 400));
        jLayeredPane2.add(lblMainBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 600, 400));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(616, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExitActionPerformed
    {//GEN-HEADEREND:event_btnExitActionPerformed
        this.setVisible(false);
        frmGoodbye.setIconImage(stickman.getImage());
        frmGoodbye.setLocationRelativeTo(this);
        frmGoodbye.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnOK1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOK1ActionPerformed
    {//GEN-HEADEREND:event_btnOK1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnOK1ActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPlayActionPerformed
    {//GEN-HEADEREND:event_btnPlayActionPerformed
        this.setVisible(false);
        frmLogin.setVisible(true);
        frmLogin.setIconImage(stickman.getImage());
        frmLogin.setLocationRelativeTo(this);
        txfUsername.setText("");
        txfPassword.setText("");
    }//GEN-LAST:event_btnPlayActionPerformed

    private void txfUsernameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txfUsernameActionPerformed
    {//GEN-HEADEREND:event_txfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfUsernameActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOKActionPerformed
    {//GEN-HEADEREND:event_btnOKActionPerformed
        try
        {
            //validation of username and password, and selection of level
            String sql = "";
            String user = txfUsername.getText();
            String pass = txfPassword.getText();
            sql = "SELECT * FROM LoginDetails WHERE Username = '" + user + "' AND Password = '" + pass + "';";
            ResultSet rs = connect.query(sql);
            if (rs.next())
            {
                if (user.equals(rs.getString("Username")) && pass.equals(rs.getString("Password")))
                {
                    refresh();
                    frmLogin.setVisible(false);
                    frmPlay.setVisible(true);
                    frmPlay.setIconImage(stickman.getImage());
                    frmPlay.setLocationRelativeTo(this);
                    play.setUsername(user);
                    play.setPassword(pass);
                    Object[] lvls =
                    {
                        "1", "2", "3"
                    };
                    lvl = JOptionPane.showInputDialog(null, "Choose level:", "Level", JOptionPane.OK_OPTION, stickman, lvls, lvls[0]);
                    if (lvl == null)
                    {
                        frmPlay.setVisible(false);
                        setVisible(true);
                        setLocationRelativeTo(frmPlay);
                    }
                } else
                {
                    JOptionPane.showMessageDialog(this, "Incorrect username or password.");
                }

            } else
            {
                JOptionPane.showMessageDialog(this, "Incorrect username or password.");
            }

        } catch (SQLException ex)
        {
            Logger.getLogger(HangmanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        phrases1 = 0;
        phrases2 = 0;
        phrases3 = 0;
        String sql = "";
        String[] gamePhrases = new String[100];
        int count = 0;

        //choose random phrase in level 1
        if (lvl == "1")
        {
            sql = "SELECT * FROM tblPhrases where Level = 1";
            ResultSet rs = connect.query(sql);
            try
            {
                while (rs.next())
                {
                    gamePhrases[count] = rs.getString("Phrases");
                    count++;
                }
                int choice = (int) (Math.random() * ((count - 1) - 0 + 1) + 0);
                play.setWord(gamePhrases[choice]);
                System.out.println(play.getWord());
                play.setLevel(1);
                for (int i = 0; i < (play.getWord().length()); i++)
                {
                    String temp = "" + play.getWord().charAt(i);
                    if (temp.equals(" "))
                    {
                        display += " ";
                    } else if (temp.chars().allMatch(Character::isLetter))
                    {
                        display += "-";
                    }
                }
            } catch (SQLException ex)
            {
                Logger.getLogger(HangmanGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        //choose random phrase in level 2
        if (lvl == "2")
        {
            sql = "SELECT * FROM tblPhrases where Level = 2";
            ResultSet rs = connect.query(sql);
            try
            {
                while (rs.next())
                {
                    gamePhrases[count] = rs.getString("Phrases");
                    count++;
                }
                int choice = (int) (Math.random() * ((count - 1) - 0 + 1) + 0);
                play.setWord(gamePhrases[choice]);
                System.out.println(play.getWord());
                play.setLevel(2);
                for (int i = 0; i < (play.getWord().length()); i++)
                {
                    String temp = "" + play.getWord().charAt(i);
                    if (temp.equals(" "))
                    {
                        display += " ";
                    } else if (temp.chars().allMatch(Character::isLetter))
                    {
                        display += "-";
                    }
                }
            } catch (SQLException ex)
            {
                Logger.getLogger(HangmanGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //choose random phrase in level 3
        if (lvl == "3")
        {
            sql = "SELECT * FROM tblPhrases where Level = 3";
            ResultSet rs = connect.query(sql);
            try
            {
                while (rs.next())
                {
                    gamePhrases[count] = rs.getString("Phrases");
                    count++;
                }
                int choice = (int) (Math.random() * ((count - 1) - 0 + 1) + 0);
                play.setWord(gamePhrases[choice]);
                System.out.println(play.getWord());
                play.setLevel(3);
                for (int i = 0; i < (play.getWord().length()); i++)
                {
                    String temp = "" + play.getWord().charAt(i);
                    if (temp.equals(" "))
                    {
                        display += " ";
                    } else if (temp.chars().allMatch(Character::isLetter))
                    {
                        display += "-";
                    }
                }
            } catch (SQLException ex)
            {
                Logger.getLogger(HangmanGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        frmPlay.setEnabled(true);
        frmPlay.setAlwaysOnTop(true);
        frmPlay.setAlwaysOnTop(false);
        play.setGuesses(6);
        lblWord.setText(" " + display);
        lblGuesses.setText(" " + "Guesses left: " + play.getGuesses());
        lblDisplayScore.setText(" " + "Score: " + play.getScore());
    }//GEN-LAST:event_btnOKActionPerformed

    private void txfDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txfDeleteActionPerformed
    {//GEN-HEADEREND:event_txfDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDeleteActionPerformed

    private void btnHighScoresActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnHighScoresActionPerformed
    {//GEN-HEADEREND:event_btnHighScoresActionPerformed
        this.setVisible(false);
        frmHighscores.setVisible(true);
        frmHighscores.setIconImage(stickman.getImage());
        frmHighscores.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnHighScoresActionPerformed

    private void btnWordEditorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnWordEditorActionPerformed
    {//GEN-HEADEREND:event_btnWordEditorActionPerformed
        this.setVisible(false);
        frmWordEditor.setVisible(true);
        frmWordEditor.setIconImage(stickman.getImage());
        frmWordEditor.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnWordEditorActionPerformed

    private void txfUpdate2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txfUpdate2ActionPerformed
    {//GEN-HEADEREND:event_txfUpdate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfUpdate2ActionPerformed

    private void txfUpdateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txfUpdateActionPerformed
    {//GEN-HEADEREND:event_txfUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfUpdateActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegisterActionPerformed
    {//GEN-HEADEREND:event_btnRegisterActionPerformed
        //display frmRegister
        frmLogin.setVisible(false);
        frmRegister.setVisible(true);
        frmRegister.setIconImage(stickman.getImage());
        frmRegister.setLocationRelativeTo(this);
        txfRegisterUser.setText("");
        txfRegisterPass.setText("");
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnRegister2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegister2ActionPerformed
    {//GEN-HEADEREND:event_btnRegister2ActionPerformed
        //check if username is taken, if not, register
        String sql = "SELECT * FROM LoginDetails WHERE Username LIKE '" + txfRegisterUser.getText() + "';";
        ResultSet rs = connect.query(sql);
        int count = 0;
        try
        {
            while (rs.next())
            {
                count++;
            }
            if (count == 1)
            {
                JOptionPane.showMessageDialog(this, "Username taken.");
            } else if (count == 0)
            {
                if (txfRegisterUser.getText().equals("") || txfRegisterPass.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(this, "Enter a username and password.");
                } else if (txfRegisterUser.getText().length() < 13)
                {
                    sql = "INSERT INTO LoginDetails (Username, Password) VALUES ('"
                            + txfRegisterUser.getText() + "', '"
                            + txfRegisterPass.getText() + "');";

                    int records = connect.update(sql);

                    JOptionPane.showMessageDialog(this, records + " record inserted");
                    frmRegister.setVisible(false);
                    frmLogin.setVisible(true);
                } else if (txfRegisterUser.getText().length() >= 13)
                {
                    JOptionPane.showMessageDialog(this, "Username must not exceed 12 characters.");
                }
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(HangmanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegister2ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackActionPerformed
    {//GEN-HEADEREND:event_btnBackActionPerformed
        frmWordEditor.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBack2ActionPerformed
    {//GEN-HEADEREND:event_btnBack2ActionPerformed
        frmHighscores.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnOKWinActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOKWinActionPerformed
    {//GEN-HEADEREND:event_btnOKWinActionPerformed
        String sql = "";
        int current = 0;
        //score calculation for level 1
        if (lvl == "1")
        {
            sql = "SELECT Highscore1 FROM LoginDetails WHERE Username LIKE '" + play.getUsername() + "';";
            ResultSet rs = connect.query(sql);
            try
            {
                while (rs.next())
                {
                    current = rs.getInt("Highscore1");
                }
            } catch (SQLException ex)
            {
                Logger.getLogger(HangmanGUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (current < play.getScore())
            {
                sql = "UPDATE LoginDetails SET Highscore1 = " + play.getScore() + " WHERE Username LIKE '" + play.getUsername() + "';";
                int records = connect.update(sql);
                JOptionPane.showMessageDialog(this, "NEW HIGHSCORE!!! Well done!");
            }
        }
        //score calculation for level 2
        if (lvl == "2")
        {
            sql = "SELECT Highscore2 FROM LoginDetails WHERE Username LIKE '" + play.getUsername() + "';";
            ResultSet rs = connect.query(sql);
            try
            {
                while (rs.next())
                {
                    current = rs.getInt("Highscore2");
                }
            } catch (SQLException ex)
            {
                Logger.getLogger(HangmanGUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (current < play.getScore())
            {
                sql = "UPDATE LoginDetails SET Highscore2 = " + play.getScore() + " WHERE Username LIKE '" + play.getUsername() + "';";
                int records = connect.update(sql);
                JOptionPane.showMessageDialog(this, "NEW HIGHSCORE!!! Well done!");
            }
        }
        //score calculation for level 3
        if (lvl == "3")
        {
            sql = "SELECT Highscore3 FROM LoginDetails WHERE Username LIKE '" + play.getUsername() + "';";
            ResultSet rs = connect.query(sql);
            try
            {
                while (rs.next())
                {
                    current = rs.getInt("Highscore3");
                }
            } catch (SQLException ex)
            {
                Logger.getLogger(HangmanGUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (current < play.getScore())
            {
                sql = "UPDATE LoginDetails SET Highscore3 = " + play.getScore() + " WHERE Username LIKE '" + play.getUsername() + "';";
                int records = connect.update(sql);
                JOptionPane.showMessageDialog(this, "NEW HIGHSCORE!!! Well done!");
            }
        }

        frmWin.setVisible(false);
        frmPlay.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_btnOKWinActionPerformed

    private void btnOKLossActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOKLossActionPerformed
    {//GEN-HEADEREND:event_btnOKLossActionPerformed
        frmLose.setVisible(false);
        frmPlay.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_btnOKLossActionPerformed

    private void btnLevel1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLevel1ActionPerformed
    {//GEN-HEADEREND:event_btnLevel1ActionPerformed
        try
        {
            //display highscores in level 1
            String sql = "";
            sql = "SELECT Username, Highscore1 FROM LoginDetails ORDER BY Highscore1 DESC, Username";
            ResultSet rs = connect.query(sql);
            String out = "Username" + "\t\t" + "Score" + "\t\t" + "\n";
            while (rs.next())
            {
                String name = rs.getString("Username");
                String score = rs.getString("Highscore1");

                out += name + "\t\t"
                        + score + "\t\t"
                        + "\n";
            }
            txaHighscores.setText(out);
        } catch (SQLException ex)
        {
            Logger.getLogger(HangmanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLevel1ActionPerformed

    private void btnLevel2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLevel2ActionPerformed
    {//GEN-HEADEREND:event_btnLevel2ActionPerformed
        try
        {
            //display highscores in level 2
            String sql = "";
            sql = "SELECT Username, Highscore2 FROM LoginDetails ORDER BY Highscore2 DESC, Username";
            ResultSet rs = connect.query(sql);
            String out = "Username" + "\t\t" + "Score" + "\t\t" + "\n";
            while (rs.next())
            {
                String name = rs.getString("Username");
                String score = rs.getString("Highscore2");

                out += name + "\t\t"
                        + score + "\t\t"
                        + "\n";
            }
            txaHighscores.setText(out);
        } catch (SQLException ex)
        {
            Logger.getLogger(HangmanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLevel2ActionPerformed

    private void btnLevel3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLevel3ActionPerformed
    {//GEN-HEADEREND:event_btnLevel3ActionPerformed
        try
        {
            //display highscores in level 3
            String sql = "";
            sql = "SELECT Username, Highscore3 FROM LoginDetails ORDER BY Highscore3 DESC, Username";
            ResultSet rs = connect.query(sql);
            String out = "Username" + "\t\t" + "Score" + "\t\t" + "\n";
            while (rs.next())
            {
                String name = rs.getString("Username");
                String score = rs.getString("Highscore3");

                out += name + "\t\t"
                        + score + "\t\t"
                        + "\n";
            }
            txaHighscores.setText(out);
        } catch (SQLException ex)
        {
            Logger.getLogger(HangmanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLevel3ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClearActionPerformed
    {//GEN-HEADEREND:event_btnClearActionPerformed
        //reset all highscores
        String sql = "";
        sql = "UPDATE LoginDetails SET Highscore1 = '0', Highscore2 = '0', Highscore3 = '0';";
        int clear = JOptionPane.showConfirmDialog(this, "Are you sure?", "CLEAR ALL", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (clear == 0)
        {
            int records = connect.update(sql);
            txaHighscores.setText("All highscores have been set to 0.");
        } else if (clear == 1)
        {
            txaHighscores.setText("No change has been made.");
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn1ActionPerformed
    {//GEN-HEADEREND:event_btn1ActionPerformed
        try
        {
            //display phrases in level 1
            String sql = "";
            sql = "SELECT Phrases FROM tblPhrases WHERE Level LIKE '1' ORDER BY Phrases ASC;";
            ResultSet rs = connect.query(sql);
            String out = "No.\t" + "Phrase:\n";
            int pos = 1;
            while (rs.next())
            {
                String phrase = rs.getString("Phrases");

                out += pos + ".\t" + phrase
                        + "\n";
                pos++;
            }
            txaWordEditorView.setText(out);
        } catch (SQLException ex)
        {
            Logger.getLogger(HangmanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn2ActionPerformed
    {//GEN-HEADEREND:event_btn2ActionPerformed
        try
        {
            //display phrases in level 2
            String sql = "";
            sql = "SELECT Phrases FROM tblPhrases WHERE Level LIKE '2' ORDER BY Phrases ASC;";
            ResultSet rs = connect.query(sql);
            String out = "No.\t" + "Phrase:\n";
            int pos = 1;
            while (rs.next())
            {
                String phrase = rs.getString("Phrases");

                out += pos + ".\t" + phrase
                        + "\n";
                pos++;
            }
            txaWordEditorView.setText(out);
        } catch (SQLException ex)
        {
            Logger.getLogger(HangmanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn3ActionPerformed
    {//GEN-HEADEREND:event_btn3ActionPerformed
        try
        {
            //display phrases in level 3
            String sql = "";
            sql = "SELECT Phrases FROM tblPhrases WHERE Level LIKE '3' ORDER BY Phrases ASC;";
            ResultSet rs = connect.query(sql);
            String out = "No.\t" + "Phrase:\n";
            int pos = 1;
            while (rs.next())
            {
                String phrase = rs.getString("Phrases");

                out += pos + ".\t" + phrase
                        + "\n";
                pos++;
            }
            txaWordEditorView.setText(out);
        } catch (SQLException ex)
        {
            Logger.getLogger(HangmanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnInsertActionPerformed
    {//GEN-HEADEREND:event_btnInsertActionPerformed
        //validate and insert phrase into selected level
        String sql = "";
        String word = txfInsert.getText();
        String level = "";
        if (cmbInsert.getSelectedItem() == "Level 1")
        {
            level = "1";
        } else if (cmbInsert.getSelectedItem() == "Level 2")
        {
            level = "2";
        } else if (cmbInsert.getSelectedItem() == "Level 3")
        {
            level = "3";
        }
        sql = "INSERT INTO tblPhrases (Phrases, Level) VALUES ('" + word.toLowerCase() + "', '" + level + "');";
        if (word.chars().allMatch(Character::isLetter) || word.contains(" "))
        {
            int records = connect.update(sql);
            JOptionPane.showMessageDialog(this, records + " record/s inserted");
        } else if (!word.chars().allMatch(Character::isLetter))
        {
            JOptionPane.showMessageDialog(this, "Word may only contain letters and spaces.");
        }

    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUpdateActionPerformed
    {//GEN-HEADEREND:event_btnUpdateActionPerformed
        //update current phrase with new validated phrase into selected level
        String sql = "";
        String oldWord = txfUpdate.getText();
        String newWord = txfUpdate2.getText();
        String level = "";
        if (cmbInsert.getSelectedItem() == "Level 1")
        {
            level = "1";
        } else if (cmbInsert.getSelectedItem() == "Level 2")
        {
            level = "2";
        } else if (cmbInsert.getSelectedItem() == "Level 3")
        {
            level = "3";
        }

        if (newWord.chars().allMatch(Character::isLetter))
        {
            sql = "UPDATE tblPhrases SET Phrases = '" + newWord + "' WHERE Phrases = '" + oldWord + "' AND Level = '" + level + "';";
            int records = connect.update(sql);
            JOptionPane.showMessageDialog(this, records + " record/s updated");
        } else if (!newWord.chars().allMatch(Character::isLetter))
        {
            JOptionPane.showMessageDialog(this, "Word may only contain letters.");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeleteActionPerformed
    {//GEN-HEADEREND:event_btnDeleteActionPerformed
        //delete phrase from selected level
        String sql = "";
        String oldWord = txfDelete.getText();
        String level = "";
        if (cmbDelete.getSelectedItem() == "Level 1")
        {
            level = "1";
        } else if (cmbDelete.getSelectedItem() == "Level 2")
        {
            level = "2";
        } else if (cmbDelete.getSelectedItem() == "Level 3")
        {
            level = "3";
        }
        sql = "DELETE FROM tblPhrases WHERE Phrases = '" + oldWord + "' AND Level = '" + level + "';";
        int records = connect.update(sql);
        JOptionPane.showMessageDialog(this, records + " record/s deleted");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnActionPerformed
    {//GEN-HEADEREND:event_btnActionPerformed
        //Main method play
        JButton temp = (JButton) evt.getSource();
        display = play.calculateGuess(temp.getText(), play.getWord(), display);
        lblWord.setText(" " + display);
        lblGuesses.setText(" " + "Guesses left: " + play.getGuesses());
        lblDisplayScore.setText(" " + "Score: " + play.getScore());
        int hanged = play.getGuesses();
        if (!display.contains("-"))
        {
            frmPlay.setEnabled(false);
            frmWin.setVisible(true);
            frmWin.setIconImage(stickman.getImage());
            frmWin.setLocationRelativeTo(this);
            lblScore.setText("Score: " + play.getScore());
            lblGoodJob.setText("Good job " + play.getUsername() + "!");
        } else if (display.contains("-"))
        {
            switch (hanged)
            {
                case 5:
                    lblHead.setIcon(head);
                    break;
                case 4:
                    lblBody.setIcon(body);
                    break;
                case 3:
                    lblArm1.setIcon(arm1);
                    break;
                case 2:
                    lblArm2.setIcon(arm2);
                    break;
                case 1:
                    lblLeg1.setIcon(leg1);
                    break;
                case 0:
                    lblLeg2.setIcon(leg2);
                    frmPlay.setEnabled(false);
                    frmLose.setVisible(true);
                    frmLose.setIconImage(stickman.getImage());
                    frmLose.setLocationRelativeTo(this);
                    lblFailedWord.setText(play.getWord());
            }
        }
        temp.setEnabled(false);
    }//GEN-LAST:event_btnActionPerformed

    private void btnCancelRegisterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelRegisterActionPerformed
    {//GEN-HEADEREND:event_btnCancelRegisterActionPerformed
        frmRegister.setVisible(false);
        frmLogin.setVisible(true);
    }//GEN-LAST:event_btnCancelRegisterActionPerformed

    private void btnBackLoginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackLoginActionPerformed
    {//GEN-HEADEREND:event_btnBackLoginActionPerformed
        frmLogin.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_btnBackLoginActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeleteUserActionPerformed
    {//GEN-HEADEREND:event_btnDeleteUserActionPerformed
        //delete selected profile if confirmed
        int confirm = JOptionPane.showConfirmDialog(this, "Delete profile?", "Delete account", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (confirm == 0)
        {
            String sql = "DELETE FROM LoginDetails WHERE Username LIKE '" + txfDeleteUser.getText() + "';";
            int update = connect.update(sql);
            if (update == 0)
            {
                txaHighscores.setText("No profiles were deleted.");
            }
            if (update == 1)
            {
                txaHighscores.setText("Profile " + txfDeleteUser.getText() + " deleted.");
            }
        } else if (confirm == 1)
        {
            txaHighscores.setText("No changes have been made.");
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnExitGameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExitGameActionPerformed
    {//GEN-HEADEREND:event_btnExitGameActionPerformed
        frmPlay.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_btnExitGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(HangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(HangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(HangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(HangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new HangmanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnBackLogin;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCancelRegister;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExitGame;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnHighScores;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnLevel1;
    private javax.swing.JButton btnLevel2;
    private javax.swing.JButton btnLevel3;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnOK1;
    private javax.swing.JButton btnOKLoss;
    private javax.swing.JButton btnOKWin;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegister2;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnWordEditor;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JComboBox<String> cmbDelete;
    private javax.swing.JComboBox<String> cmbInsert;
    private javax.swing.JComboBox<String> cmbUpdate;
    private javax.swing.JFrame frmGoodbye;
    private javax.swing.JFrame frmHighscores;
    private javax.swing.JFrame frmLogin;
    private javax.swing.JFrame frmLose;
    private javax.swing.JFrame frmPlay;
    private javax.swing.JFrame frmRegister;
    private javax.swing.JFrame frmWin;
    private javax.swing.JFrame frmWordEditor;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblArm1;
    private javax.swing.JLabel lblArm2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackground1;
    private javax.swing.JLabel lblBody;
    private javax.swing.JLabel lblDisplayScore;
    private javax.swing.JLabel lblFailedWord;
    private javax.swing.JLabel lblGoodJob;
    private javax.swing.JLabel lblGuesses;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblHighscoresBackground;
    private javax.swing.JLabel lblHighscoresTitle;
    private javax.swing.JLabel lblLeg1;
    private javax.swing.JLabel lblLeg2;
    private javax.swing.JLabel lblLossBackground;
    private javax.swing.JLabel lblMainBackground;
    private javax.swing.JLabel lblParchment;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPlayBackground;
    private javax.swing.JLabel lblRegisterBackground;
    private javax.swing.JLabel lblRegisterPass;
    private javax.swing.JLabel lblRegisterUser;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblSorry;
    private javax.swing.JLabel lblSorryFace;
    private javax.swing.JLabel lblThanks;
    private javax.swing.JLabel lblThumbsUp;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWavingHand;
    private javax.swing.JLabel lblWinBackground;
    private javax.swing.JLabel lblWord;
    private javax.swing.JLabel lblWordEditorBackground;
    private javax.swing.JLabel lblWordEditorTitle;
    private javax.swing.JTextArea txaHighscores;
    private javax.swing.JTextArea txaWordEditorView;
    private javax.swing.JTextField txfDelete;
    private javax.swing.JTextField txfDeleteUser;
    private javax.swing.JTextField txfInsert;
    private javax.swing.JTextField txfPassword;
    private javax.swing.JTextField txfRegisterPass;
    private javax.swing.JTextField txfRegisterUser;
    private javax.swing.JTextField txfUpdate;
    private javax.swing.JTextField txfUpdate2;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
